### ISSUE TITLE
Hospedagem

### ISSUE THREAD

**Issue by yagopeixinho** [Allisson-Lima-Dev/game-mario-broz-web#1]
Existe a possibilidade de hospedar esse site em algum lugar?

**Comment by allisson-lima** [comment]
@yagopeixinho  sim meu nobre, pode ser pelo gitHub pages ou qualquer outro que tenha hospedagem gratuito, uso o Netlify.
Ainda irei implementar a responsividade dele com controles para mobile em breve.

**Comment by yagopeixinho** [comment]
Eu gosto muito do netlify

**Comment by allisson-lima** [comment]
Show mano, qualquer dúvida só chamar.
